package:
  name: asc_ode_bla
  version: "0.1.0"

source:
  path: .

build:
  noarch: python
  script: python -m pip install .

requirements:
  build:
    - python
    - pip
    - setuptools
    - scikit-build-core
  host:
    - python
  run:
    - python

about:
  home: ""
  license: MIT
  summary: "ASC ODE BLA pybind11 bindings for Pyodide"
